export { Header } from "./Header.jsx";
export { Footer } from "./Footer.jsx";
export { DisplayPicture } from "./DisplayPicture.jsx";
export { SocialMediaBar } from "./SocialMediaBar.jsx";
export { TechSkillsList } from "./TechSkillsList.jsx";
export { BlogCard } from "./BlogCard.jsx";
export { Company } from "./Company.jsx";
export { Designation } from "./Designation.jsx";
export { Markdown } from "./Markdown.jsx";
